### ISSUE TITLE
CommonUI incompatibility

### ISSUE THREAD

**Issue by saim80** [unraed/DialogueTree#2]
How to Reproduce
============

1. Build dialogue display widget with CommonUI components such as CommonTextBlock.
2. Set project settings to use the new dialogue display widget.
3. Quit and relaunch the Unreal Editor.
4. Observe crash due to Class loading failure.

Due to the fact that UDialogueSettings uses TSubclassOf<...> for both dialogue controller and dialogue widget type variables, the mentioned classes are being directly loaded although CommonUI module is not loaded yet.

Possible Solution
===========

I fixed the issue by replacing TSubclassOf<...> to TSoftClassPtr<...> for my local copy.

**Comment by unraed** [comment]
Hi Sangwoo,

Thanks for reaching out to let me know about this. I had no idea there was
an incompatibility here, but I'll get it patched with the next update.
Thanks again!

Best,
Zach (Unraed)

**Comment by saim80** [comment]
I confirmed the fix. Thanks for the update!
